name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/Celloc.DataTable.sln
    - name: Build
      run: dotnet build --no-restore src/Celloc.DataTable.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Celloc.DataTable.sln
