name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Get
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} src/Celloc.DataTable.sln
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build src/Celloc.DataTable.sln
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . src/Celloc.DataTable.sln
    - name: Push
      run: dotnet nuget push Celloc.DataTable.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
